In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv("spaceship-titanic/train.csv")

In [3]:
train.duplicated().sum()

np.int64(0)

In [4]:
train.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
7158,7639_01,Europa,True,B/290/S,55 Cancri e,44.0,False,0.0,0.0,0.0,NaN,0.0,Wimps Invebodene,True

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   str
 1   HomePlanet    8492 non-null   str
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   str
 4   Destination   8511 non-null   str
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   str
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 891.5+ KB

In [6]:
train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [7]:
(train.isnull().sum() / len(train)) * 100

PassengerId     0.000000
HomePlanet      2.312205
CryoSleep       2.496261
Cabin           2.289198
Destination     2.093639
Age             2.059128
VIP             2.335212
RoomService     2.082135
FoodCourt       2.105142
ShoppingMall    2.392730
Spa             2.105142
VRDeck          2.162660
Name            2.300702
Transported     0.000000
dtype: float64

In [8]:
print(train["CryoSleep"].mode())
train["CryoSleep"]=train["CryoSleep"].fillna(False)

0    False
Name: CryoSleep, dtype: object

In [9]:
print(train["HomePlanet"].mode())
train["HomePlanet"]=train["HomePlanet"].fillna("Earth")

0    Earth
Name: HomePlanet, dtype: str

In [10]:
print(train["Cabin"].mode())
train["Cabin"]=train["Cabin"].fillna("G/734/S")

0    G/734/S
Name: Cabin, dtype: str

In [11]:
print(train["Destination"].mode())
train["Destination"]=train["Destination"].fillna("TRAPPIST-1e")

0    TRAPPIST-1e
Name: Destination, dtype: str

In [12]:
print(train["VIP"].mode())
train["VIP"]=train["VIP"].fillna(False)

0    False
Name: VIP, dtype: object

In [13]:
# Numerical columns
# filled every null value of num or numerical columns at once 
# the fillna will find the mean of every train num columns 
num_cols = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
train[num_cols] = train[num_cols].fillna(train[num_cols].mean())

In [14]:
train=train.drop(columns=["Name"])

In [15]:
test=pd.read_csv("spaceship-titanic/test.csv")

In [16]:
test.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
97,0218_01,Earth,False,G/35/P,TRAPPIST-1e,19.0,False,741.0,12.0,1.0,0.0,0.0,Jenne Alshipson

In [17]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   str
 1   HomePlanet    4190 non-null   str
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   str
 4   Destination   4185 non-null   str
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   str
dtypes: float64(6), object(2), str(5)
memory usage: 434.5+ KB

In [18]:
test.isnull().sum()

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [19]:
(test.isnull().sum() / len(test)) * 100

PassengerId     0.000000
HomePlanet      2.034136
CryoSleep       2.174421
Cabin           2.338087
Destination     2.151040
Age             2.127660
VIP             2.174421
RoomService     1.917232
FoodCourt       2.478373
ShoppingMall    2.291326
Spa             2.361468
VRDeck          1.870470
Name            2.197802
dtype: float64

In [20]:
print(test["HomePlanet"].mode())
test["HomePlanet"]=test["HomePlanet"].fillna("Earth")

0    Earth
Name: HomePlanet, dtype: str

In [21]:
print(test["CryoSleep"].mode())
test["CryoSleep"]=test["CryoSleep"].fillna(False)

0    False
Name: CryoSleep, dtype: object

In [22]:
print(test["Cabin"].mode())
test["Cabin"]=test["Cabin"].fillna("G/160/P")

0    G/160/P
Name: Cabin, dtype: str

In [23]:
print(test["Destination"].mode())
test["Destination"]=test["Destination"].fillna("TRAPPIST-1e")

0    TRAPPIST-1e
Name: Destination, dtype: str

In [24]:
print(test["VIP"].mode())
test["VIP"]=test["VIP"].fillna(False)

0    False
Name: VIP, dtype: object

In [25]:
number_cols = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
test[number_cols] = test[number_cols].fillna(test[number_cols].mean())

In [26]:
test=test.drop(columns=["Name"])

In [27]:
test.duplicated().sum()

np.int64(0)

In [28]:
# ENCORDING converying cat to num 
# We encode categorical text data into numbers because most machine learning algorithms can only work with numbers, not text.
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

In [29]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Transported'],
      dtype='str')

In [30]:
train["Destination"]=LE.fit_transform(train["Destination"])
print(train["Destination"])

0       2
1       2
2       2
3       2
4       2
       ..
8688    0
8689    1
8690    2
8691    0
8692    2
Name: Destination, Length: 8693, dtype: int64

In [31]:
train["Cabin"]=LE.fit_transform(train["Cabin"])
print(train["Cabin"])

0        149
1       2184
2          1
3          1
4       2186
        ...
8688     146
8689    5280
8690    5285
8691    2131
8692    2131
Name: Cabin, Length: 8693, dtype: int64

In [32]:
train["VIP"]=LE.fit_transform(train["VIP"])
print(train["VIP"])

0       0
1       0
2       1
3       0
4       0
       ..
8688    1
8689    0
8690    0
8691    0
8692    0
Name: VIP, Length: 8693, dtype: int64

In [33]:
train["CryoSleep"]=LE.fit_transform(train["CryoSleep"])
print(train["CryoSleep"])

0       0
1       0
2       0
3       0
4       0
       ..
8688    0
8689    1
8690    0
8691    0
8692    0
Name: CryoSleep, Length: 8693, dtype: int64

In [34]:
train["HomePlanet"]=LE.fit_transform(train["HomePlanet"])
print(train["HomePlanet"])

0       1
1       0
2       1
3       1
4       0
       ..
8688    1
8689    0
8690    0
8691    1
8692    1
Name: HomePlanet, Length: 8693, dtype: int64

In [35]:
train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,0001_01,1,0,149,2,39.0,0,0.0,0.0,0.0,0.0,0.0,False
1,0002_01,0,0,2184,2,24.0,0,109.0,9.0,25.0,549.0,44.0,True
2,0003_01,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,False
3,0003_02,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,False
4,0004_01,0,0,2186,2,16.0,0,303.0,70.0,151.0,565.0,2.0,True

In [36]:
X_train=train.iloc[:,:-1]

In [37]:
y_train=train["Transported"]

In [38]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier()

In [39]:
DTC.fit(X_train,y_train)

DecisionTreeClassifier()

In [40]:
DTC.predict(X_train)

array([False,  True, False, ...,  True, False,  True], shape=(8693,))

In [41]:
DTC.score(X_train,y_train)

1.0

In [42]:
test.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'],
      dtype='str')

In [43]:
test.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
1410,3016_01,Earth,False,G/490/P,TRAPPIST-1e,6.0,False,0.0,0.0,0.0,0.0,0.0

In [44]:
test["Destination"]=LE.fit_transform(test["Destination"])
print(test["Destination"])

0       2
1       2
2       0
3       2
4       2
       ..
4272    2
4273    2
4274    0
4275    2
4276    1
Name: Destination, Length: 4277, dtype: int64

In [45]:
test["Cabin"]=LE.fit_transform(test["Cabin"])
print(test["Cabin"])

0       2784
1       1867
2        257
3        259
4       1940
        ...
4272    2679
4273    2691
4274     602
4275     603
4276    2680
Name: Cabin, Length: 4277, dtype: int64

In [46]:
test["HomePlanet"]=LE.fit_transform(test["HomePlanet"])
print(test["HomePlanet"])

0       0
1       0
2       1
3       1
4       0
       ..
4272    0
4273    0
4274    2
4275    1
4276    0
Name: HomePlanet, Length: 4277, dtype: int64

In [47]:
test["CryoSleep"]=LE.fit_transform(test["CryoSleep"])
print(test["CryoSleep"])

0       1
1       0
2       1
3       0
4       0
       ..
4272    1
4273    0
4274    1
4275    0
4276    1
Name: CryoSleep, Length: 4277, dtype: int64

In [48]:
test["VIP"]=LE.fit_transform(test["VIP"])
print(test["VIP"])

0       0
1       0
2       0
3       0
4       0
       ..
4272    0
4273    0
4274    0
4275    0
4276    0
Name: VIP, Length: 4277, dtype: int64

In [49]:
X_test=test.iloc[:,0:]

In [50]:
y_pred=DTC.predict(X_test)

In [51]:
PassengerID=test["PassengerId"]
di={"PassengerId":PassengerID,
    "Transported": y_pred}


subnission=pd.DataFrame(di)

In [52]:
subnission.head()

  PassengerId  Transported
0     0013_01        False
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True

In [53]:
subnission.to_csv("subnission.csv",index=False)